version: '3.8'

services:
  # Node.js API and Web UI
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/beemap
    depends_on:
      - db
    restart: unless-stopped

  # Python services for analysis
  python:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/beemap
    depends_on:
      - db
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beemap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@beemap.pro
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: 